

import { Translation, ColorPalette } from './types';

export const COLOR_PALETTES: Record<string, ColorPalette> = {
  green: {
    50: '#f0fdf4',
    100: '#dcfce7',
    200: '#bbf7d0',
    300: '#86efac',
    400: '#4ade80',
    500: '#22c55e',
    600: '#16a34a',
    700: '#15803d',
    800: '#166534',
    900: '#14532d',
  },
  blue: {
    50: '#eff6ff',
    100: '#dbeafe',
    200: '#bfdbfe',
    300: '#93c5fd',
    400: '#60a5fa',
    500: '#3b82f6',
    600: '#2563eb',
    700: '#1d4ed8',
    800: '#1e40af',
    900: '#1e3a8a',
  },
  purple: {
    50: '#f5f3ff',
    100: '#ede9fe',
    200: '#ddd6fe',
    300: '#c4b5fd',
    400: '#a78bfa',
    500: '#8b5cf6',
    600: '#7c3aed',
    700: '#6d28d9',
    800: '#5b21b6',
    900: '#4c1d95',
  },
  orange: {
    50: '#fff7ed',
    100: '#ffedd5',
    200: '#fed7aa',
    300: '#fdba74',
    400: '#fb923c',
    500: '#f97316',
    600: '#ea580c',
    700: '#c2410c',
    800: '#9a3412',
    900: '#7c2d12',
  },
  pink: {
    50: '#fdf2f8',
    100: '#fce7f3',
    200: '#fbcfe8',
    300: '#f9a8d4',
    400: '#f472b6',
    500: '#ec4899',
    600: '#db2777',
    700: '#be185d',
    800: '#9d174d',
    900: '#831843',
  },
  red: {
    50: '#fef2f2',
    100: '#fee2e2',
    200: '#fecaca',
    300: '#fca5a5',
    400: '#f87171',
    500: '#ef4444',
    600: '#dc2626',
    700: '#b91c1c',
    800: '#991b1b',
    900: '#7f1d1d',
  },
  yellow: {
    50: '#fefce8',
    100: '#fef9c3',
    200: '#fef08a',
    300: '#fde047',
    400: '#facc15',
    500: '#eab308',
    600: '#ca8a04',
    700: '#a16207',
    800: '#854d0e',
    900: '#713f12',
  },
  brown: {
    50: '#efebe9',
    100: '#d7ccc8',
    200: '#bcaaa4',
    300: '#a1887f',
    400: '#8d6e63',
    500: '#795548',
    600: '#6d4c41',
    700: '#5d4037',
    800: '#4e342e',
    900: '#3e2723',
  }
};

export const TRANSLATIONS: Record<string, Translation> = {
  en: {
    title: 'Smart_Nutri',
    subtitle: 'Smart Nutrition',
    scanButton: 'Scan Food',
    uploadButton: 'Upload Photo',
    analyzing: 'Analyzing your food...',
    history: 'History',
    noHistory: 'No recent scans found.',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
    sugar: 'Sugar',
    save: 'Save to History',
    back: 'Back',
    tryAgain: 'Try Again',
    errorGeneric: 'Could not identify food. Please try again.',
    errorApiKey: 'API Key missing.',
    errorQuota: 'API quota exceeded. Please wait a few minutes and try again.',
    favorites: 'Favorites',
    dailyGoal: 'Daily Goal',
    viewHistory: 'View Full History',
    totalCalories: 'Total Calories',
    totalScans: 'Total Items',

    bioimpedanceBtn: 'Bioimpedance & Diet',
    bioimpedanceTitle: 'Body & Diet Calculator',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    age: 'Age (years)',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    activity: 'Activity Level',
    goal: 'Goal',
    calculate: 'Calculate Plan',
    recalculate: 'Edit Stats',
    yourBmi: 'Your BMI',
    idealWeight: 'Ideal Weight',
    dailyNeeds: 'Daily Calorie Target',
    dietPlan: 'Your Diet Plan',
    
    actSedentary: 'Sedentary (Little or no exercise)',
    actLight: 'Lightly Active (Exercise 1-3 days/week)',
    actModerate: 'Moderately Active (Exercise 3-5 days/week)',
    actActive: 'Active (Exercise 6-7 days/week)',
    actVeryActive: 'Very Active (Hard exercise/physical job)',
    
    goalLose: 'Lose Weight (-500 kcal)',
    goalMaintain: 'Maintain Weight',
    goalGain: 'Gain Muscle (+500 kcal)',

    todayProgress: "Today's Progress",
    caloriesRemaining: 'Remaining',
    caloriesOver: 'Over Limit',
    goalMet: 'Goal Met!',

    chooseColor: 'Choose Theme Color',

    addDescriptionTitle: 'Describe the Food',
    addDescriptionPlaceholder: 'E.g., Homemade lasagna with extra cheese...',
    analyzeNow: 'Analyze Now',
    optional: '(Optional)',
    
    calendar: 'Calendar',
    hasData: 'Has data',
    noData: 'No data',
    dayDetails: 'Day Details',
    dailyTotals: 'Daily Totals',
    foodItems: 'Food Items',
    noDataForDay: 'No data recorded for this day',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    
    // Water Tracker
    water: 'Water',
    waterGoal: 'Daily Water Goal',
    waterRemaining: 'Remaining',
    waterGoalMet: 'Goal Met!',
    waterLow: 'Low Hydration',
    waterAdd: 'Add Water',
    waterToday: 'Today',
    waterReminder: 'Water Reminder',
    waterReminderTitle: 'Time to Drink Water!',
    waterReminderMessage: 'Stay hydrated! Remember to drink water regularly.',
    waterReminderAction: 'I Drank Water',
    waterReminderSnooze: 'Remind Me Later',
    waterReminderInterval: 'Reminder Interval',
    waterNotificationTitle: '💧 Time to Drink Water!',
    waterNotificationBody: 'Stay hydrated! Remember to drink water regularly.',
    waterQuickAdd: 'Quick Add',
    waterCustom: 'Custom Amount',
    waterHistory: 'Water History',
    waterStats: 'Water Stats',
  },
  pt: {
    title: 'Smart_Nutri',
    subtitle: 'Nutrição Inteligente',
    scanButton: 'Escanear Alimento',
    uploadButton: 'Carregar Foto',
    analyzing: 'Analisando seu prato...',
    history: 'Histórico',
    noHistory: 'Nenhum escaneamento recente.',
    calories: 'Calorias',
    protein: 'Proteínas',
    carbs: 'Carboidratos',
    fat: 'Gorduras',
    fiber: 'Fibras',
    sugar: 'Açúcar',
    save: 'Salvar no Histórico',
    back: 'Voltar',
    tryAgain: 'Tentar Novamente',
    errorGeneric: 'Não foi possível identificar. Tente novamente.',
    errorApiKey: 'Chave API ausente.',
    errorQuota: 'Cota da API excedida. Aguarde alguns minutos e tente novamente.',
    favorites: 'Favoritos',
    dailyGoal: 'Meta Diária',
    viewHistory: 'Ver Histórico Completo',
    totalCalories: 'Total de Calorias',
    totalScans: 'Total de Itens',

    bioimpedanceBtn: 'Bioimpedância e Dieta',
    bioimpedanceTitle: 'Calculadora de Dieta',
    gender: 'Gênero',
    male: 'Masculino',
    female: 'Feminino',
    age: 'Idade (anos)',
    height: 'Altura (cm)',
    weight: 'Peso (kg)',
    activity: 'Nível de Atividade',
    goal: 'Objetivo',
    calculate: 'Calcular Plano',
    recalculate: 'Editar Dados',
    yourBmi: 'Seu IMC',
    idealWeight: 'Peso Ideal',
    dailyNeeds: 'Meta de Calorias Diárias',
    dietPlan: 'Seu Plano de Dieta',
    
    actSedentary: 'Sedentário (Pouco ou nenhum exercício)',
    actLight: 'Levemente Ativo (Exercício 1-3 dias/sem)',
    actModerate: 'Moderadamente Ativo (Exercício 3-5 dias/sem)',
    actActive: 'Muito Ativo (Exercício 6-7 days/sem)',
    actVeryActive: 'Extremamente Ativo (Trabalho físico/treino pesado)',
    
    goalLose: 'Perder Peso (-500 kcal)',
    goalMaintain: 'Manter Peso',
    goalGain: 'Ganhar Massa (+500 kcal)',

    todayProgress: 'Progresso Hoje',
    caloriesRemaining: 'Restantes',
    caloriesOver: 'Acima da Meta',
    goalMet: 'Meta Atingida!',

    chooseColor: 'Escolha a Cor do Tema',

    addDescriptionTitle: 'Descreva o Alimento',
    addDescriptionPlaceholder: 'Ex: Lasanha caseira com queijo extra...',
    analyzeNow: 'Analisar Agora',
    optional: '(Opcional)',
    
    calendar: 'Calendário',
    hasData: 'Com dados',
    noData: 'Sem dados',
    dayDetails: 'Detalhes do Dia',
    dailyTotals: 'Totais Diários',
    foodItems: 'Itens Alimentares',
    noDataForDay: 'Nenhum dado registrado para este dia',
    day: 'Dia',
    week: 'Semana',
    month: 'Mês',
    
    // Water Tracker
    water: 'Água',
    waterGoal: 'Meta Diária de Água',
    waterRemaining: 'Restante',
    waterGoalMet: 'Meta Atingida!',
    waterLow: 'Hidratação Baixa',
    waterAdd: 'Adicionar Água',
    waterToday: 'Hoje',
    waterReminder: 'Lembrete de Água',
    waterReminderTitle: 'Hora de Beber Água!',
    waterReminderMessage: 'Mantenha-se hidratado! Lembre-se de beber água regularmente.',
    waterReminderAction: 'Bebi Água',
    waterReminderSnooze: 'Lembrar Depois',
    waterReminderInterval: 'Intervalo de Lembrete',
    waterNotificationTitle: '💧 Hora de Beber Água!',
    waterNotificationBody: 'Mantenha-se hidratado! Lembre-se de beber água regularmente.',
    waterQuickAdd: 'Adição Rápida',
    waterCustom: 'Quantidade Personalizada',
    waterHistory: 'Histórico de Água',
    waterStats: 'Estatísticas de Água',
  }
};

export const MOCK_HISTORY = [
  {
    id: '1',
    foodName: 'Avocado Toast',
    foodNameEn: 'Avocado Toast',
    foodNamePt: 'Torrada com Abacate',
    calories: 250,
    protein: 6,
    carbs: 20,
    fat: 18,
    fiber: 8,
    sugar: 1,
    description: 'Sourdough bread topped with mashed avocado and seasonings.',
    descriptionEn: 'Sourdough bread topped with mashed avocado and seasonings.',
    descriptionPt: 'Pão de fermentação natural com abacate amassado e temperos.',
    timestamp: Date.now() - 10000000
  },
  {
    id: '2',
    foodName: 'Grilled Chicken Salad',
    foodNameEn: 'Grilled Chicken Salad',
    foodNamePt: 'Salada de Frango Grelhado',
    calories: 320,
    protein: 35,
    carbs: 12,
    fat: 10,
    fiber: 5,
    sugar: 4,
    description: 'Mixed greens with grilled chicken breast and vinaigrette.',
    descriptionEn: 'Mixed greens with grilled chicken breast and vinaigrette.',
    descriptionPt: 'Mix de folhas verdes com peito de frango grelhado e vinagrete.',
    timestamp: Date.now() - 5000000
  }
];